import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Space_Grotesk, Outfit } from "next/font/google";
import "./globals.css";

export const outfit = Outfit({ subsets: ["latin"] });
export const space = Space_Grotesk({ subsets: ["latin"] });
export const jetbrains = JetBrains_Mono({ subsets: ["latin"], weight: ['600', '700'] });

export const metadata: Metadata = {
  title: "Art.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
